# Generated by Django 5.1.6 on 2025-02-19 09:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('prof', models.CharField(max_length=100)),
                ('study_work', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=18, unique=True)),
                ('passport', models.CharField(max_length=11, unique=True)),
                ('given', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Администратор'), ('bibliographer', 'Библиограф'), ('chief', 'Руководитель клубного формирования'), ('user', 'Пользователь'), ('guest', 'Гость')], max_length=50, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание роли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество страниц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image_book', models.ImageField(blank=True, null=True, upload_to='book/')),
                ('file_book', models.FileField(blank=True, null=True, upload_to='book/')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_books', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено пользователем')),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books_by', to=settings.AUTH_USER_MODEL, verbose_name='Взято на чтение')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата взятия')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Возвращена')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books_book', to='main.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взятая книга',
                'verbose_name_plural': 'Взятые книги',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('concert', 'Концерт'), ('lecture', 'Лекция'), ('workshop', 'Мастер-класс'), ('meetup', 'Встреча'), ('other', 'Другое')], max_length=50, verbose_name='Тип мероприятия')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество зрителей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('participants', models.ManyToManyField(blank=True, related_name='events_participated', to=settings.AUTH_USER_MODEL, verbose_name='Зрители')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.role', verbose_name='Роль'),
        ),
    ]
